export const NOT_CONFIGURED_STRING = "<PLEASE CONFIGURE>";

export const DEFAULT_HOST_PARAMETERS: typeof process.env = {
    LOCALHOST_PREFIX: "127.0.0",
    LOCALHOST_EXT: "1",
    DB_ENDPOINT: NOT_CONFIGURED_STRING,
    DB_NAME: NOT_CONFIGURED_STRING,
    DB_PASSWORD: NOT_CONFIGURED_STRING,
    DB_USERNAME: NOT_CONFIGURED_STRING,
    PORT: "8081",
    LOGGING_DETAIL: "2",
    NODE_ENV: 'development'
};

export const DEFAULT_TCP_PORT = 7070;

export const DEFAULT_HTTP_PORT = 3000;